import 'models/add_pet_step_4_four_model.dart';import 'package:flutter/material.dart';import 'package:inaam_s_application1/core/app_export.dart';import 'package:inaam_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:inaam_s_application1/widgets/custom_elevated_button.dart';import 'package:inaam_s_application1/widgets/custom_icon_button.dart';import 'provider/add_pet_step_4_four_provider.dart';class AddPetStep4FourScreen extends StatefulWidget {const AddPetStep4FourScreen({Key? key}) : super(key: key);

@override AddPetStep4FourScreenState createState() =>  AddPetStep4FourScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => AddPetStep4FourProvider(), child: AddPetStep4FourScreen()); } 
 }
class AddPetStep4FourScreenState extends State<AddPetStep4FourScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildVideoCamera(context), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 25.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [_buildStepFortyFour(context), SizedBox(height: 27.v), Divider(indent: 9.h, endIndent: 13.h), SizedBox(height: 19.v), CustomImageView(imagePath: ImageConstant.imgMobile, height: 69.v, width: 70.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 13.h)), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Container(width: 254.h, margin: EdgeInsets.only(left: 16.h, right: 66.h), child: Text("msg_mish_2_years_old".tr, maxLines: 6, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71)))), SizedBox(height: 26.v), _buildConfirm(context), SizedBox(height: 2.v)]))])))); } 
/// Section Widget
Widget _buildVideoCamera(BuildContext context) { return SizedBox(height: 95.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 10.v), padding: EdgeInsets.symmetric(horizontal: 65.h, vertical: 7.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgVideoCameraBlack900, height: 17.v, width: 24.h, margin: EdgeInsets.only(top: 52.v)), Padding(padding: EdgeInsets.only(top: 52.v, right: 1.h), child: Text("msg_not_connected_to".tr, style: CustomTextStyles.labelLargeMedium))]))), Align(alignment: Alignment.topCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(bottom: 34.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.fillOnSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: Row(children: [Padding(padding: EdgeInsets.only(top: 1.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlueGray, onTap: () {onTapBtnClose(context);}, child: CustomImageView(imagePath: ImageConstant.imgClose))), Padding(padding: EdgeInsets.only(left: 112.h, top: 1.v), child: Text("lbl_review".tr, style: CustomTextStyles.titleMediumWhiteA700))]))), CustomAppBar(height: 50.v, title: Container(height: 50.adaptSize, width: 50.adaptSize, margin: EdgeInsets.only(left: 14.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 50.adaptSize, width: 50.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.only(topLeft: Radius.circular(10.h), bottomRight: Radius.circular(10.h))))), CustomImageView(imagePath: ImageConstant.imgMegaphone, height: 30.adaptSize, width: 30.adaptSize, alignment: Alignment.center, margin: EdgeInsets.all(10.h))])), actions: [Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 7.h, top: 13.v, bottom: 13.v), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgUserGray900, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center), Align(alignment: Alignment.topRight, child: Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.fromLTRB(14.h, 1.v, 2.h, 15.v), decoration: BoxDecoration(color: appTheme.red400, borderRadius: BorderRadius.circular(4.h))))])), Container(height: 50.adaptSize, width: 50.adaptSize, margin: EdgeInsets.only(left: 23.h, right: 7.h), decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(25.h)))])])); } 
/// Section Widget
Widget _buildStepFortyFour(BuildContext context) { return Container(margin: EdgeInsets.only(left: 9.h), padding: EdgeInsets.symmetric(horizontal: 4.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_step_4_4".tr, style: theme.textTheme.labelMedium), SizedBox(height: 9.v), Text("msg_congratz_your_pet".tr, style: CustomTextStyles.titleMediumGray900Bold), SizedBox(height: 10.v), Container(width: 313.h, margin: EdgeInsets.only(right: 6.h), child: Text("msg_please_don_t_forget".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumErrorContainer_3.copyWith(height: 1.50))), SizedBox(height: 10.v), Container(width: 297.h, margin: EdgeInsets.only(right: 22.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_more_detailed_pet2".tr, style: CustomTextStyles.bodyMediumErrorContainer_2.copyWith(height: 1.50)), TextSpan(text: "lbl_be_their_voice".tr, style: CustomTextStyles.titleSmallErrorContainer)]), textAlign: TextAlign.left))])); } 
/// Section Widget
Widget _buildConfirm(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 13.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 50.v, width: 56.h, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.outlineBlackTL10, child: CustomImageView(imagePath: ImageConstant.imgGroupBlack900)), Expanded(child: CustomElevatedButton(text: "lbl_confirm".tr, margin: EdgeInsets.only(left: 18.h)))])); } 

/// Navigates to the previous screen.
onTapBtnClose(BuildContext context) { NavigatorService.goBack(); } 
 }
